---
kind: pipeline
name: default

steps:
- name: build for Linux
  image: rust:latest
  commands:
  - apt-get update && apt-get install libprocps-dev
  - cargo build --release
---
kind: signature
hmac: 8cf10f7d07bef8b089c0f56638dccfaeef3a98e8ca11a27a411a2a8554f4bee0

...
