---
kind: pipeline
name: default

steps:
- name: build for Linux
  image: rust:latest
  commands:
  - cargo build --release
---
kind: signature
hmac: 4b9b8dc348d4d694758245c4964d59fe30af2334028e84f9be75a4e9b9975439

...
